version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Setup Environment Value
          command: echo 'export CIRCLE_TAG="22.0-20220216"' > $BASH_ENV
      - run:
          name: Show Environment Value
          command: echo $CIRCLE_TAG
      - run:
          name: Build
          command: docker build -f bitcoind/dockerfile -t ${OWNER}/${IMAGE_NAME}:latest .
      - run:
          name: Docker Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Tag From latest To $CIRCLE_TAG
          command: docker tag ${OWNER}/${IMAGE_NAME}:latest ${OWNER}/${IMAGE_NAME}:$CIRCLE_TAG
      - run:
          name: Push image to registory
          command: docker push ${OWNER}/${IMAGE_NAME}:latest
#      - add_ssh_keys:
#          fingerprints:
#            - $SSH_KEY_FINGERPRINT
      